# Android Gradle Plugin 8.9 Configuration

# AndroidX
android.useAndroidX=true
android.enableJetifier=false

# R8
android.enableR8.fullMode=true

# Gradle
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4608m

# Build features
android.nonTransitiveRClass=false
android.defaults.buildfeatures.resvalues=true

# SDK
android.suppressUnsupportedCompileSdk=36

# Kotlin
android.builtInKotlin=false
